export const ARTIST_WORDS: { id: string; word: string }[] = [
  { id: "cat", word: "貓" },
  { id: "dog", word: "狗" },
  { id: "fox", word: "狐狸" },
  { id: "rabbit", word: "兔子" },
  { id: "hamster", word: "倉鼠" },
  { id: "guinea", word: "天竺鼠" },
  { id: "cow", word: "牛" },
  { id: "buffalo", word: "水牛" },
  { id: "rhino", word: "犀牛" },
  { id: "horse", word: "馬" },
  { id: "zebra", word: "斑馬" },
  { id: "donkey", word: "驢" },
  { id: "sheep", word: "綿羊" },
  { id: "goat", word: "山羊" },
  { id: "alpaca", word: "羊駝" },
  { id: "goldfish", word: "金魚" },
  { id: "koi", word: "鯉魚" },
  { id: "fish", word: "魚" },
  { id: "dolphin", word: "海豚" },
  { id: "whale", word: "鯨魚" },
  { id: "shark", word: "鯊魚" },
  { id: "chicken", word: "雞" },
  { id: "duck", word: "鴨" },
  { id: "goose", word: "鵝" },
  { id: "penguin", word: "企鵝" },
  { id: "seagull", word: "海鷗" },
  { id: "pigeon", word: "鴿子" },
  { id: "panda", word: "熊貓" },
  { id: "koala", word: "無尾熊" },
  { id: "raccoon", word: "浣熊" },
  { id: "tiger", word: "老虎" },
  { id: "lion", word: "獅子" },
  { id: "leopard", word: "豹" },
  { id: "pig", word: "豬" },
  { id: "boar", word: "山豬" },
  { id: "hippo", word: "河馬" },
  { id: "frog", word: "青蛙" },
  { id: "toad", word: "蟾蜍" },
  { id: "lizard", word: "蜥蜴" },
  { id: "crab", word: "螃蟹" },
  { id: "lobster", word: "龍蝦" },
  { id: "shrimp", word: "蝦子" },
  { id: "turtle", word: "烏龜" },
  { id: "beetle", word: "甲蟲" },
  { id: "snail", word: "蝸牛" },
  { id: "bee", word: "蜜蜂" },
  { id: "fly", word: "蒼蠅" },
  { id: "mosquito", word: "蚊子" },
  { id: "butterfly", word: "蝴蝶" },
  { id: "moth", word: "飛蛾" },
  { id: "dragonfly", word: "蜻蜓" },
  { id: "mouse", word: "老鼠" },
  { id: "squirrel", word: "松鼠" },
  { id: "chipmunk", word: "花栗鼠" },
  { id: "snake", word: "蛇" },
  { id: "worm", word: "蚯蚓" },
  { id: "eel", word: "鰻魚" },
  { id: "octopus", word: "章魚" },
  { id: "squid", word: "魷魚" },
  { id: "jellyfish", word: "水母" },
  { id: "apple", word: "蘋果" },
  { id: "peach", word: "桃子" },
  { id: "plum", word: "李子" },
  { id: "orange", word: "橘子" },
  { id: "lemon", word: "檸檬" },
  { id: "tangerine", word: "柳丁" },
  { id: "banana", word: "香蕉" },
  { id: "corn", word: "玉米" },
  { id: "cucumber", word: "小黃瓜" },
  { id: "cake", word: "蛋糕" },
  { id: "pudding", word: "布丁" },
  { id: "cupcake", word: "杯子蛋糕" },
  { id: "donut", word: "甜甜圈" },
  { id: "bagel", word: "貝果" },
  { id: "wreath", word: "花圈" },
  { id: "bun", word: "包子" },
  { id: "mantou", word: "饅頭" },
  { id: "dumpling", word: "餃子" },
  { id: "burger", word: "漢堡" },
  { id: "sandwich", word: "三明治" },
  { id: "hotdog", word: "熱狗" },
  { id: "pizza", word: "披薩" },
  { id: "pie", word: "派" },
  { id: "omelette", word: "蛋餅" },
  { id: "icecream", word: "冰淇淋" },
  { id: "softserve", word: "霜淇淋" },
  { id: "sundae", word: "聖代" },
  { id: "onigiri", word: "飯糰" },
  { id: "sushi", word: "壽司" },
  { id: "nigiri", word: "握壽司" },
  { id: "cup", word: "馬克杯" },
  { id: "teacup", word: "茶杯" },
  { id: "mug", word: "水杯" },
  { id: "bowl", word: "碗" },
  { id: "plate", word: "盤子" },
  { id: "pot", word: "鍋子" },
  { id: "bottle", word: "瓶子" },
  { id: "kettle", word: "水壺" },
  { id: "thermos", word: "保溫瓶" },
  { id: "sun", word: "太陽" },
  { id: "moon", word: "月亮" },
  { id: "clock", word: "時鐘" },
  { id: "house", word: "房子" },
  { id: "castle", word: "城堡" },
  { id: "temple", word: "神廟" },
  { id: "car", word: "汽車" },
  { id: "taxi", word: "計程車" },
  { id: "bus", word: "公車" },
  { id: "truck", word: "卡車" },
  { id: "firetruck", word: "消防車" },
  { id: "garbage", word: "垃圾車" },
  { id: "bike", word: "腳踏車" },
  { id: "scooter", word: "機車" },
  { id: "moto", word: "摩托車" },
  { id: "umbrella", word: "雨傘" },
  { id: "parasol", word: "陽傘" },
  { id: "oilpaper", word: "油紙傘" },
  { id: "hat", word: "帽子" },
  { id: "helmet", word: "頭盔" },
  { id: "crown", word: "皇冠" },
  { id: "mushroom", word: "蘑菇" },
  { id: "lampshade", word: "燈罩" },
  { id: "cap", word: "鴨舌帽" },
  { id: "chair", word: "椅子" },
  { id: "stool", word: "凳子" },
  { id: "barstool", word: "高腳椅" },
  { id: "fork", word: "叉子" },
  { id: "spoon", word: "湯匙" },
  { id: "chopsticks", word: "筷子" },
  { id: "phone", word: "手機" },
  { id: "tablet", word: "平板" },
  { id: "frame", word: "相框" },
  { id: "pencil", word: "鉛筆" },
  { id: "pen", word: "原子筆" },
  { id: "crayon", word: "蠟筆" },
  { id: "rocket", word: "火箭" },
  { id: "missile", word: "飛彈" },
  { id: "firework", word: "沖天炮" },
  { id: "tree", word: "樹" },
  { id: "xmas", word: "聖誕樹" },
  { id: "palm", word: "棕櫚樹" },
  { id: "flower", word: "花" },
  { id: "tulip", word: "鬱金香" },
  { id: "rose", word: "玫瑰" },
  { id: "cactus", word: "仙人掌" },
  { id: "succulent", word: "多肉" },
  { id: "aloe", word: "蘆薈" },
  { id: "plane", word: "飛機" },
  { id: "heli", word: "直升機" },
  { id: "drone", word: "無人機" },
  { id: "boat", word: "船" },
  { id: "sail", word: "帆船" },
  { id: "sub", word: "潛水艇" },
  { id: "star", word: "星星" },
  { id: "snow", word: "雪花" },
  { id: "gear", word: "齒輪" },
  { id: "heart", word: "愛心" },
  { id: "drop", word: "水滴" },
  { id: "leaf", word: "葉子" },
  { id: "glasses", word: "眼鏡" },
  { id: "goggles", word: "護目鏡" },
  { id: "divemask", word: "潛水鏡" },
  { id: "bag", word: "包包" },
  { id: "backpack", word: "背包" },
  { id: "luggage", word: "行李箱" },
  { id: "shoe", word: "鞋子" },
  { id: "boot", word: "靴子" },
  { id: "slipper", word: "拖鞋" },
  { id: "guitar", word: "吉他" },
  { id: "violin", word: "小提琴" },
  { id: "ukulele", word: "烏克麗麗" },
  { id: "drum", word: "鼓" },
  { id: "tambourine", word: "鈴鼓" },
  { id: "bell", word: "鈴鐺" },
  { id: "ball", word: "球" },
  { id: "basketball", word: "籃球" },
  { id: "watermelon", word: "西瓜" },
  { id: "laptop", word: "筆電" },
  { id: "tv", word: "電視" },
  { id: "microwave", word: "微波爐" },
  { id: "bridge", word: "橋" },
  { id: "arch", word: "拱門" },
  { id: "rainbow", word: "彩虹" },
  { id: "mountain", word: "山" },
  { id: "volcano", word: "火山" },
  { id: "pyramid", word: "金字塔" },
  { id: "cloud", word: "雲" },
  { id: "cotton", word: "棉花糖" },
  { id: "smoke", word: "煙" },
  { id: "ghost", word: "幽靈" },
  { id: "snowman", word: "雪人" },
  { id: "robot", word: "機器人" },
  { id: "sword", word: "劍" },
  { id: "knife", word: "刀" },
  { id: "dagger", word: "匕首" },
  { id: "scissors", word: "剪刀" },
  { id: "plier", word: "鉗子" },
  { id: "clip", word: "夾子" },
  { id: "axe", word: "斧頭" },
  { id: "hammer", word: "錘子" },
  { id: "mallet", word: "木槌" },
  { id: "kite", word: "風箏" },
  { id: "paperplane", word: "紙飛機" },
  { id: "glider", word: "滑翔翼" },
  { id: "ring", word: "戒指" },
  { id: "watch", word: "手錶" },
  { id: "bracelet", word: "手環" },
];

/** 每一組三個題目外形要接近，畫歪了才不容易猜。 */
export const ARTIST_SETS: string[][] = [
  ["cat", "dog", "fox"],
  ["rabbit", "hamster", "guinea"],
  ["cow", "buffalo", "rhino"],
  ["horse", "zebra", "donkey"],
  ["sheep", "goat", "alpaca"],
  ["goldfish", "koi", "fish"],
  ["dolphin", "whale", "shark"],
  ["chicken", "duck", "goose"],
  ["penguin", "seagull", "pigeon"],
  ["panda", "koala", "raccoon"],
  ["tiger", "lion", "leopard"],
  ["pig", "boar", "hippo"],
  ["frog", "toad", "lizard"],
  ["crab", "lobster", "shrimp"],
  ["turtle", "beetle", "snail"],
  ["bee", "fly", "mosquito"],
  ["butterfly", "moth", "dragonfly"],
  ["mouse", "squirrel", "chipmunk"],
  ["snake", "worm", "eel"],
  ["octopus", "squid", "jellyfish"],
  ["apple", "peach", "plum"],
  ["orange", "lemon", "tangerine"],
  ["banana", "corn", "cucumber"],
  ["cake", "pudding", "cupcake"],
  ["donut", "bagel", "wreath"],
  ["bun", "mantou", "dumpling"],
  ["burger", "sandwich", "hotdog"],
  ["pizza", "pie", "omelette"],
  ["icecream", "softserve", "sundae"],
  ["onigiri", "sushi", "nigiri"],
  ["cup", "teacup", "mug"],
  ["bowl", "plate", "pot"],
  ["bottle", "kettle", "thermos"],
  ["sun", "moon", "clock"],
  ["house", "castle", "temple"],
  ["car", "taxi", "bus"],
  ["truck", "firetruck", "garbage"],
  ["bike", "scooter", "moto"],
  ["umbrella", "parasol", "oilpaper"],
  ["hat", "helmet", "crown"],
  ["mushroom", "umbrella", "lampshade"],
  ["chair", "stool", "barstool"],
  ["fork", "spoon", "chopsticks"],
  ["phone", "tablet", "frame"],
  ["pencil", "pen", "crayon"],
  ["rocket", "missile", "firework"],
  ["tree", "xmas", "palm"],
  ["flower", "tulip", "rose"],
  ["cactus", "succulent", "aloe"],
  ["plane", "heli", "drone"],
  ["boat", "sail", "sub"],
  ["star", "snow", "gear"],
  ["heart", "drop", "leaf"],
  ["glasses", "goggles", "divemask"],
  ["bag", "backpack", "luggage"],
  ["shoe", "boot", "slipper"],
  ["guitar", "violin", "ukulele"],
  ["drum", "tambourine", "bell"],
  ["ball", "basketball", "watermelon"],
  ["laptop", "tv", "microwave"],
  ["bridge", "arch", "rainbow"],
  ["mountain", "volcano", "pyramid"],
  ["cloud", "cotton", "smoke"],
  ["ghost", "snowman", "robot"],
  ["sword", "knife", "dagger"],
  ["scissors", "plier", "clip"],
  ["axe", "hammer", "mallet"],
  ["kite", "paperplane", "glider"],
  ["ring", "watch", "bracelet"],
];

export function artistWord(id: string): string {
  return ARTIST_WORDS.find((w) => w.id === id)?.word ?? "？";
}
