/** Color is the card BACKGROUND only. White-background cards are decoys. */
export const REACT_COLORS = ["lime", "red", "cyan", "blue", "gold", "orange", "violet"] as const;
export type ReactColor = (typeof REACT_COLORS)[number];

export const REACT_COLOR_META: Record<ReactColor, { name: string; hex: string }> = {
  lime: { name: "綠", hex: "#18d020" },
  red: { name: "紅", hex: "#ec080c" },
  cyan: { name: "青", hex: "#0D8CFD" },
  blue: { name: "藍", hex: "#04106C" },
  gold: { name: "金", hex: "#ffd24a" },
  orange: { name: "橘", hex: "#fc7204" },
  violet: { name: "紫", hex: "#A820D2" },
};

export const REACT_CARDS: { file: string; color: ReactColor }[] = [
  { file: "lime-001.jpg", color: "lime" },
  { file: "lime-002.jpg", color: "lime" },
  { file: "lime-003.jpg", color: "lime" },
  { file: "lime-004.jpg", color: "lime" },
  { file: "lime-005.jpg", color: "lime" },
  { file: "lime-006.jpg", color: "lime" },
  { file: "lime-007.jpg", color: "lime" },
  { file: "lime-008.jpg", color: "lime" },
  { file: "lime-009.jpg", color: "lime" },
  { file: "lime-010.jpg", color: "lime" },
  { file: "lime-011.jpg", color: "lime" },
  { file: "lime-012.jpg", color: "lime" },
  { file: "lime-013.jpg", color: "lime" },
  { file: "lime-014.jpg", color: "lime" },
  { file: "lime-015.jpg", color: "lime" },
  { file: "lime-016.jpg", color: "lime" },
  { file: "lime-017.jpg", color: "lime" },
  { file: "lime-018.jpg", color: "lime" },
  { file: "lime-019.jpg", color: "lime" },
  { file: "lime-020.jpg", color: "lime" },
  { file: "lime-021.jpg", color: "lime" },
  { file: "lime-022.jpg", color: "lime" },
  { file: "lime-023.jpg", color: "lime" },
  { file: "lime-024.jpg", color: "lime" },
  { file: "lime-025.jpg", color: "lime" },
  { file: "lime-026.jpg", color: "lime" },
  { file: "lime-027.jpg", color: "lime" },
  { file: "lime-028.jpg", color: "lime" },
  { file: "lime-029.jpg", color: "lime" },
  { file: "lime-030.jpg", color: "lime" },
  { file: "lime-031.jpg", color: "lime" },
  { file: "lime-032.jpg", color: "lime" },
  { file: "lime-033.jpg", color: "lime" },
  { file: "lime-034.jpg", color: "lime" },
  { file: "lime-035.jpg", color: "lime" },
  { file: "lime-036.jpg", color: "lime" },
  { file: "lime-037.jpg", color: "lime" },
  { file: "lime-038.jpg", color: "lime" },
  { file: "lime-039.jpg", color: "lime" },
  { file: "lime-040.jpg", color: "lime" },
  { file: "lime-041.jpg", color: "lime" },
  { file: "lime-042.jpg", color: "lime" },
  { file: "red-001.jpg", color: "red" },
  { file: "red-002.jpg", color: "red" },
  { file: "red-003.jpg", color: "red" },
  { file: "red-004.jpg", color: "red" },
  { file: "red-005.jpg", color: "red" },
  { file: "red-006.jpg", color: "red" },
  { file: "red-007.jpg", color: "red" },
  { file: "red-008.jpg", color: "red" },
  { file: "red-009.jpg", color: "red" },
  { file: "red-010.jpg", color: "red" },
  { file: "red-011.jpg", color: "red" },
  { file: "red-012.jpg", color: "red" },
  { file: "red-013.jpg", color: "red" },
  { file: "red-014.jpg", color: "red" },
  { file: "red-015.jpg", color: "red" },
  { file: "red-016.jpg", color: "red" },
  { file: "red-017.jpg", color: "red" },
  { file: "red-018.jpg", color: "red" },
  { file: "red-019.jpg", color: "red" },
  { file: "red-020.jpg", color: "red" },
  { file: "red-021.jpg", color: "red" },
  { file: "red-022.jpg", color: "red" },
  { file: "red-023.jpg", color: "red" },
  { file: "red-024.jpg", color: "red" },
  { file: "red-025.jpg", color: "red" },
  { file: "red-026.jpg", color: "red" },
  { file: "red-027.jpg", color: "red" },
  { file: "red-028.jpg", color: "red" },
  { file: "red-029.jpg", color: "red" },
  { file: "red-030.jpg", color: "red" },
  { file: "red-031.jpg", color: "red" },
  { file: "red-032.jpg", color: "red" },
  { file: "red-033.jpg", color: "red" },
  { file: "red-034.jpg", color: "red" },
  { file: "red-035.jpg", color: "red" },
  { file: "red-036.jpg", color: "red" },
  { file: "red-037.jpg", color: "red" },
  { file: "red-038.jpg", color: "red" },
  { file: "red-039.jpg", color: "red" },
  { file: "red-040.jpg", color: "red" },
  { file: "red-041.jpg", color: "red" },
  { file: "red-042.jpg", color: "red" },
  { file: "red-043.jpg", color: "red" },
  { file: "red-044.jpg", color: "red" },
  { file: "cyan-001.jpg", color: "cyan" },
  { file: "cyan-002.jpg", color: "cyan" },
  { file: "cyan-003.jpg", color: "cyan" },
  { file: "cyan-004.jpg", color: "cyan" },
  { file: "cyan-005.jpg", color: "cyan" },
  { file: "cyan-006.jpg", color: "cyan" },
  { file: "cyan-007.jpg", color: "cyan" },
  { file: "cyan-008.jpg", color: "cyan" },
  { file: "cyan-009.jpg", color: "cyan" },
  { file: "cyan-010.jpg", color: "cyan" },
  { file: "cyan-011.jpg", color: "cyan" },
  { file: "cyan-012.jpg", color: "cyan" },
  { file: "cyan-013.jpg", color: "cyan" },
  { file: "cyan-014.jpg", color: "cyan" },
  { file: "cyan-015.jpg", color: "cyan" },
  { file: "cyan-016.jpg", color: "cyan" },
  { file: "cyan-017.jpg", color: "cyan" },
  { file: "cyan-018.jpg", color: "cyan" },
  { file: "cyan-019.jpg", color: "cyan" },
  { file: "cyan-020.jpg", color: "cyan" },
  { file: "cyan-021.jpg", color: "cyan" },
  { file: "cyan-022.jpg", color: "cyan" },
  { file: "cyan-023.jpg", color: "cyan" },
  { file: "cyan-024.jpg", color: "cyan" },
  { file: "cyan-025.jpg", color: "cyan" },
  { file: "cyan-026.jpg", color: "cyan" },
  { file: "cyan-027.jpg", color: "cyan" },
  { file: "cyan-028.jpg", color: "cyan" },
  { file: "cyan-029.jpg", color: "cyan" },
  { file: "cyan-030.jpg", color: "cyan" },
  { file: "cyan-031.jpg", color: "cyan" },
  { file: "cyan-032.jpg", color: "cyan" },
  { file: "cyan-033.jpg", color: "cyan" },
  { file: "blue-001.jpg", color: "blue" },
  { file: "blue-002.jpg", color: "blue" },
  { file: "blue-003.jpg", color: "blue" },
  { file: "blue-004.jpg", color: "blue" },
  { file: "blue-005.jpg", color: "blue" },
  { file: "blue-006.jpg", color: "blue" },
  { file: "blue-007.jpg", color: "blue" },
  { file: "blue-008.jpg", color: "blue" },
  { file: "blue-009.jpg", color: "blue" },
  { file: "blue-010.jpg", color: "blue" },
  { file: "blue-011.jpg", color: "blue" },
  { file: "blue-012.jpg", color: "blue" },
  { file: "blue-013.jpg", color: "blue" },
  { file: "blue-014.jpg", color: "blue" },
  { file: "blue-015.jpg", color: "blue" },
  { file: "blue-016.jpg", color: "blue" },
  { file: "blue-017.jpg", color: "blue" },
  { file: "blue-018.jpg", color: "blue" },
  { file: "blue-019.jpg", color: "blue" },
  { file: "blue-020.jpg", color: "blue" },
  { file: "blue-021.jpg", color: "blue" },
  { file: "blue-022.jpg", color: "blue" },
  { file: "blue-023.jpg", color: "blue" },
  { file: "blue-024.jpg", color: "blue" },
  { file: "blue-025.jpg", color: "blue" },
  { file: "blue-026.jpg", color: "blue" },
  { file: "blue-027.jpg", color: "blue" },
  { file: "blue-028.jpg", color: "blue" },
  { file: "blue-029.jpg", color: "blue" },
  { file: "blue-030.jpg", color: "blue" },
  { file: "blue-031.jpg", color: "blue" },
  { file: "blue-032.jpg", color: "blue" },
  { file: "blue-033.jpg", color: "blue" },
  { file: "gold-001.jpg", color: "gold" },
  { file: "gold-002.jpg", color: "gold" },
  { file: "gold-003.jpg", color: "gold" },
  { file: "gold-004.jpg", color: "gold" },
  { file: "gold-005.jpg", color: "gold" },
  { file: "gold-006.jpg", color: "gold" },
  { file: "gold-007.jpg", color: "gold" },
  { file: "gold-008.jpg", color: "gold" },
  { file: "gold-009.jpg", color: "gold" },
  { file: "gold-010.jpg", color: "gold" },
  { file: "gold-011.jpg", color: "gold" },
  { file: "gold-012.jpg", color: "gold" },
  { file: "gold-013.jpg", color: "gold" },
  { file: "gold-014.jpg", color: "gold" },
  { file: "gold-015.jpg", color: "gold" },
  { file: "gold-016.jpg", color: "gold" },
  { file: "gold-017.jpg", color: "gold" },
  { file: "gold-018.jpg", color: "gold" },
  { file: "gold-019.jpg", color: "gold" },
  { file: "gold-020.jpg", color: "gold" },
  { file: "gold-021.jpg", color: "gold" },
  { file: "gold-022.jpg", color: "gold" },
  { file: "gold-023.jpg", color: "gold" },
  { file: "gold-024.jpg", color: "gold" },
  { file: "gold-025.jpg", color: "gold" },
  { file: "gold-026.jpg", color: "gold" },
  { file: "gold-027.jpg", color: "gold" },
  { file: "gold-028.jpg", color: "gold" },
  { file: "gold-029.jpg", color: "gold" },
  { file: "gold-030.jpg", color: "gold" },
  { file: "gold-031.jpg", color: "gold" },
  { file: "gold-032.jpg", color: "gold" },
  { file: "gold-033.jpg", color: "gold" },
  { file: "orange-001.jpg", color: "orange" },
  { file: "orange-002.jpg", color: "orange" },
  { file: "orange-003.jpg", color: "orange" },
  { file: "orange-004.jpg", color: "orange" },
  { file: "orange-005.jpg", color: "orange" },
  { file: "orange-006.jpg", color: "orange" },
  { file: "orange-007.jpg", color: "orange" },
  { file: "orange-008.jpg", color: "orange" },
  { file: "orange-009.jpg", color: "orange" },
  { file: "orange-010.jpg", color: "orange" },
  { file: "orange-011.jpg", color: "orange" },
  { file: "orange-012.jpg", color: "orange" },
  { file: "orange-013.jpg", color: "orange" },
  { file: "orange-014.jpg", color: "orange" },
  { file: "orange-015.jpg", color: "orange" },
  { file: "orange-016.jpg", color: "orange" },
  { file: "orange-017.jpg", color: "orange" },
  { file: "orange-018.jpg", color: "orange" },
  { file: "orange-019.jpg", color: "orange" },
  { file: "orange-020.jpg", color: "orange" },
  { file: "orange-021.jpg", color: "orange" },
  { file: "orange-022.jpg", color: "orange" },
  { file: "orange-023.jpg", color: "orange" },
  { file: "orange-024.jpg", color: "orange" },
  { file: "orange-025.jpg", color: "orange" },
  { file: "orange-026.jpg", color: "orange" },
  { file: "orange-027.jpg", color: "orange" },
  { file: "orange-028.jpg", color: "orange" },
  { file: "orange-029.jpg", color: "orange" },
  { file: "orange-030.jpg", color: "orange" },
  { file: "orange-031.jpg", color: "orange" },
  { file: "orange-032.jpg", color: "orange" },
  { file: "orange-033.jpg", color: "orange" },
  { file: "violet-001.jpg", color: "violet" },
  { file: "violet-002.jpg", color: "violet" },
  { file: "violet-003.jpg", color: "violet" },
  { file: "violet-004.jpg", color: "violet" },
  { file: "violet-005.jpg", color: "violet" },
  { file: "violet-006.jpg", color: "violet" },
  { file: "violet-007.jpg", color: "violet" },
  { file: "violet-008.jpg", color: "violet" },
  { file: "violet-009.jpg", color: "violet" },
  { file: "violet-010.jpg", color: "violet" },
  { file: "violet-011.jpg", color: "violet" },
  { file: "violet-012.jpg", color: "violet" },
  { file: "violet-013.jpg", color: "violet" },
  { file: "violet-014.jpg", color: "violet" },
  { file: "violet-015.jpg", color: "violet" },
  { file: "violet-016.jpg", color: "violet" },
  { file: "violet-017.jpg", color: "violet" },
  { file: "violet-018.jpg", color: "violet" },
  { file: "violet-019.jpg", color: "violet" },
  { file: "violet-020.jpg", color: "violet" },
  { file: "violet-021.jpg", color: "violet" },
  { file: "violet-022.jpg", color: "violet" },
  { file: "violet-023.jpg", color: "violet" },
  { file: "violet-024.jpg", color: "violet" },
  { file: "violet-025.jpg", color: "violet" },
  { file: "violet-026.jpg", color: "violet" },
  { file: "violet-027.jpg", color: "violet" },
  { file: "violet-028.jpg", color: "violet" },
  { file: "violet-029.jpg", color: "violet" },
  { file: "violet-030.jpg", color: "violet" },
  { file: "violet-031.jpg", color: "violet" },
  { file: "violet-032.jpg", color: "violet" },
  { file: "violet-033.jpg", color: "violet" },
  { file: "violet-034.jpg", color: "violet" },
  { file: "violet-035.jpg", color: "violet" },
  { file: "violet-036.jpg", color: "violet" },
  { file: "violet-037.jpg", color: "violet" },
];

/** White background. `looks` is clothing only — never a valid tap. */
export const REACT_DECOYS: { file: string; looks: ReactColor }[] = [
  { file: "decoy-001.jpg", looks: "red" },
  { file: "decoy-002.jpg", looks: "red" },
  { file: "decoy-003.jpg", looks: "red" },
  { file: "decoy-004.jpg", looks: "red" },
  { file: "decoy-005.jpg", looks: "red" },
  { file: "decoy-006.jpg", looks: "red" },
  { file: "decoy-007.jpg", looks: "red" },
  { file: "decoy-008.jpg", looks: "red" },
  { file: "decoy-009.jpg", looks: "red" },
  { file: "decoy-010.jpg", looks: "red" },
  { file: "decoy-011.jpg", looks: "red" },
  { file: "decoy-012.jpg", looks: "orange" },
  { file: "decoy-013.jpg", looks: "orange" },
  { file: "decoy-014.jpg", looks: "orange" },
  { file: "decoy-015.jpg", looks: "orange" },
  { file: "decoy-016.jpg", looks: "orange" },
  { file: "decoy-017.jpg", looks: "orange" },
  { file: "decoy-018.jpg", looks: "orange" },
  { file: "decoy-019.jpg", looks: "orange" },
  { file: "decoy-020.jpg", looks: "orange" },
  { file: "decoy-021.jpg", looks: "orange" },
  { file: "decoy-022.jpg", looks: "orange" },
  { file: "decoy-023.jpg", looks: "gold" },
  { file: "decoy-024.jpg", looks: "gold" },
  { file: "decoy-025.jpg", looks: "gold" },
  { file: "decoy-026.jpg", looks: "gold" },
  { file: "decoy-027.jpg", looks: "gold" },
  { file: "decoy-028.jpg", looks: "gold" },
  { file: "decoy-029.jpg", looks: "gold" },
  { file: "decoy-030.jpg", looks: "gold" },
  { file: "decoy-031.jpg", looks: "gold" },
  { file: "decoy-032.jpg", looks: "gold" },
  { file: "decoy-033.jpg", looks: "gold" },
  { file: "decoy-034.jpg", looks: "lime" },
  { file: "decoy-035.jpg", looks: "lime" },
  { file: "decoy-036.jpg", looks: "lime" },
  { file: "decoy-037.jpg", looks: "lime" },
  { file: "decoy-038.jpg", looks: "lime" },
  { file: "decoy-039.jpg", looks: "lime" },
  { file: "decoy-040.jpg", looks: "lime" },
  { file: "decoy-041.jpg", looks: "lime" },
  { file: "decoy-042.jpg", looks: "lime" },
  { file: "decoy-043.jpg", looks: "lime" },
  { file: "decoy-044.jpg", looks: "lime" },
  { file: "decoy-045.jpg", looks: "cyan" },
  { file: "decoy-046.jpg", looks: "cyan" },
  { file: "decoy-047.jpg", looks: "cyan" },
  { file: "decoy-048.jpg", looks: "cyan" },
  { file: "decoy-049.jpg", looks: "cyan" },
  { file: "decoy-050.jpg", looks: "cyan" },
  { file: "decoy-051.jpg", looks: "cyan" },
  { file: "decoy-052.jpg", looks: "cyan" },
  { file: "decoy-053.jpg", looks: "cyan" },
  { file: "decoy-054.jpg", looks: "cyan" },
  { file: "decoy-055.jpg", looks: "cyan" },
  { file: "decoy-056.jpg", looks: "blue" },
  { file: "decoy-057.jpg", looks: "blue" },
  { file: "decoy-058.jpg", looks: "blue" },
  { file: "decoy-059.jpg", looks: "blue" },
  { file: "decoy-060.jpg", looks: "blue" },
  { file: "decoy-061.jpg", looks: "blue" },
  { file: "decoy-062.jpg", looks: "blue" },
  { file: "decoy-063.jpg", looks: "blue" },
  { file: "decoy-064.jpg", looks: "blue" },
  { file: "decoy-065.jpg", looks: "blue" },
  { file: "decoy-066.jpg", looks: "blue" },
  { file: "decoy-067.jpg", looks: "violet" },
  { file: "decoy-068.jpg", looks: "violet" },
  { file: "decoy-069.jpg", looks: "violet" },
  { file: "decoy-070.jpg", looks: "violet" },
  { file: "decoy-071.jpg", looks: "violet" },
  { file: "decoy-072.jpg", looks: "violet" },
  { file: "decoy-073.jpg", looks: "violet" },
  { file: "decoy-074.jpg", looks: "violet" },
  { file: "decoy-075.jpg", looks: "violet" },
  { file: "decoy-076.jpg", looks: "violet" },
  { file: "decoy-077.jpg", looks: "violet" },
];

function shuffleIn<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j]!, a[i]!];
  }
  return a;
}

/** Fresh mix each deal: round-robin colors then shuffle so boards don't repeat. */
export function pickMatchFaces(n: number): { file: string; color: ReactColor }[] {
  const by = new Map<ReactColor, { file: string; color: ReactColor }[]>();
  for (const c of REACT_CARDS) {
    const list = by.get(c.color) ?? [];
    list.push(c);
    by.set(c.color, list);
  }
  const colors = shuffleIn([...by.keys()]);
  for (const col of colors) by.set(col, shuffleIn(by.get(col)!));
  const picked: { file: string; color: ReactColor }[] = [];
  const cursor: Partial<Record<ReactColor, number>> = {};
  while (picked.length < n) {
    let added = false;
    for (const col of colors) {
      if (picked.length >= n) break;
      const list = by.get(col) ?? [];
      const i = cursor[col] ?? 0;
      if (i < list.length) {
        picked.push(list[i]!);
        cursor[col] = i + 1;
        added = true;
      }
    }
    if (!added) break;
  }
  return shuffleIn(picked);
}
