import {readFile,writeFile,readdir} from 'node:fs/promises';
const results=JSON.parse(await readFile('reports/mobile-results.json','utf8'));
const version=JSON.parse(await readFile('version.json','utf8'));
const rows=[];
function collect(suites){for(const suite of suites){for(const spec of suite.specs||[])for(const test of spec.tests||[])rows.push({project:test.projectName,title:spec.title,status:test.status});collect(suite.suites||[]);}}
collect(results.suites);
const summary={generatedAt:new Date().toISOString(),version:version.version,stats:results.stats,projects:[...new Set(rows.map(r=>r.project))].map(project=>({project,passed:rows.filter(r=>r.project===project&&r.status==='expected').length,failed:rows.filter(r=>r.project===project&&r.status==='unexpected').length,skipped:rows.filter(r=>r.project===project&&r.status==='skipped').length})),deviceTesting:'Playwright mobile emulation; no physical iPhone/iPad/Android testing',multiplayer:'Unavailable: cross-origin CORS rejected; original Grok signaling HTTP 500. No successful roster/role/round synchronization. Explicit original-site fallback preserves room code.'};
await writeFile('reports/summary.json',JSON.stringify(summary,null,2)+'\n');
const shots=(await readdir('reports/screenshots')).filter(f=>f.endsWith('.png')).sort();
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const html=`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>公司酒局手機測試報告</title><style>body{font:16px/1.6 system-ui;margin:24px auto;padding:0 20px;max-width:1100px;background:#121212;color:#eee}a{color:#7ee5ef}table{border-collapse:collapse;width:100%}th,td{text-align:left;border-bottom:1px solid #555;padding:8px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:20px}figure{margin:0}img{width:100%;height:300px;object-fit:contain;background:#050505}figcaption{font-size:12px;overflow-wrap:anywhere}</style><h1>公司酒局手機測試報告</h1><p>版本 <code>${version.version}</code> · ${summary.generatedAt}</p><p><strong>Playwright 手機模擬，並非實體 iPhone、iPad 或 Android 真機測試。</strong></p><p>${results.stats.expected} 通過、${results.stats.unexpected} 失敗。${results.stats.skipped} 項略過為重複的連線故障測試，該測試每種引擎各跑一次。</p><p>多人連線實測未成功：Pages→Grok 被 CORS 阻擋，原站 signaling 回傳 HTTP 500。已採明確導引、保留房號。</p><p><a href="mobile-results.json">完整 JSON</a> · <a href="summary.json">摘要 JSON</a> · <a href="edge-results.json">啟動與錯誤測試</a> · <a href="multiplayer/results.json">雙 context 連線證據</a> · <a href="public-smoke.json">公開站 smoke test</a> · <a href="deployment-check.json">公開資產雜湊驗證</a></p><table><tr><th>引擎／尺寸或模式</th><th>通過</th><th>失敗</th></tr>${summary.projects.map(r=>`<tr><td>${esc(r.project)}</td><td>${r.passed}</td><td>${r.failed}</td></tr>`).join('')}</table><h2>各尺寸與流程截圖</h2><section>${shots.map(f=>`<figure><a href="screenshots/${encodeURIComponent(f)}"><img loading="lazy" src="screenshots/${encodeURIComponent(f)}" alt="${esc(f)}"></a><figcaption>${esc(f)}</figcaption></figure>`).join('')}</section></html>`;
await writeFile('reports/index.html',html);console.log(JSON.stringify(summary.stats));
